version: '3.10'

services:
  jupyter-lab:
    build:
      context: .
    image: jupyterlab:3.5.0
    ports:
      - 8888:8888
    environment:
      - FASTBPE=${PWD}/fastBPE
      - MOSES=${PWD}/mosesdecoder
    volumes:
      - ./src:/home/jovyan/work
